---
- name: add dovecot rpm key
  rpm_key:
    key: "{{ dovecot_repo_key }}"
  when: dovecot_repo_state

- name: "add dovecot repository"
  template:
    src: "repository-redhat.j2"
    dest: /etc/yum.repos.d/dovecot.repo
    owner: root
    group: root
    mode: 0644
  when: dovecot_repo_state

- name: "remove dovecot repository"
  file:
    path: /etc/yum.repos.d/nginx.repo
    state: absent
  when: not dovecot_repo_state
